[package]
name = "ridecontrol"
version = "0.1.0"
authors = ["Vadym S. Khondar <vadym@khondar.name>"]
edition = "2018"

[dependencies]
"termion" = "1.5.1"
"librobohat" = { path = "../librobohat" }
"librover" = { path = "../librover" }