[package]
name = "ridecontrol"
version = "0.1.0"
authors = ["Vadym S. Khondar <vadym@khondar.name>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
termion = "1.5.1"
libdriver-robohat = { path = "../libdriver-robohat" }
libdriver = { path = "../libdriver" }