[package]
name = "libutil"
version = "0.1.0"
authors = ["Vadym S. Khondar <vadym@khondar.name>"]
edition = "2021"

[dependencies]
config = "0.14.0"
log = "0.4.20"
log4rs = "1.3.0"
rppal = "0.17.1"
thiserror = "1.0.57"