[package]
name = "libutil"
version = "0.1.0"
authors = ["Vadym S. Khondar <vadym@khondar.name>"]
edition = "2018"

[dependencies]
config = "0.10.1"
log = "0.4"
log4rs = "0.9.0"
rppal = "0.9.0"
thiserror = "1.0.19"