# This builds within container of ARM arch using binfmt
# It is considerably slow.

FROM raspbian/stretch:latest AS builder

COPY ./src /rover-firmware

WORKDIR /rover-firmware

RUN wget -qO - https://sh.rustup.rs | sh -s -- -y
RUN apt update && apt -y upgrade
RUN apt install -y build-essential
RUN . $HOME/.cargo/env && \
    cargo build --release

FROM raspbian/stretch:latest

COPY --from builder /rover-firmware/target/release/api-server /api-server

ENTRYPOINT ["/api-server"]

# end
