[package]
name = "ridecontrol"
version = "0.1.0"
authors = ["Vadym S. Khondar <vadym@khondar.name>"]
edition = "2018"

[dependencies]
libdriver-robohat = { path = "../libdriver-robohat" }
libridecontrol = { path = "../libridecontrol" }
