version: '3'

services:
  wifiap:
    image: ${REPOPREFIX}wifiap:${TAG}
    restart: always
    network_mode: host
    privileged: true

  servoblaster:
    image: ${REPOPREFIX}servoblaster:${TAG}
    restart: always
    devices:
      - "/dev/mem:/dev/mem"
    volumes:
      - servoblaster:/servoblaster

  rproxy:
    image: ${REPOPREFIX}rproxy:${TAG}
    ports:
      - 80:80
    restart: always

  rover-api-net:
    image: ${REPOPREFIX}rover-api-net:${TAG}
    ports:
      - 5757:5757
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/gpiochip0:/dev/gpiochip0"
    volumes:
      - servoblaster:/extdev
    restart: always

  rover-api-http:
    image: ${REPOPREFIX}rover-api-http:${TAG}
    restart: always

volumes:
  servoblaster:

# end