version: '3'

services:
  wifiap:
    build: ./wifiap
    image: wifiap:latest
    restart: always
    network_mode: host
    privileged: true

  servoblaster:
    build: ./servoblaster
    image: servoblaster:latest
    restart: always
    privileged: true

  frontend:
    build: frontend
    image: rproxy:latest
    ports:
      - 8080:80
    restart: always

# end