version: '3'

services:
  wifiap:
    image: ${REPOPREFIX}wifiap:${TAG}
    restart: always
    network_mode: host
    privileged: true

  servoblaster:
    image: ${REPOPREFIX}servoblaster:${TAG}
    restart: always
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/vcio:/dev/vcio"
    cap_add:
      - SYS_RAWIO
    volumes:
      - servoblaster:/servoblaster

  video:
    image: ${REPOPREFIX}video:${TAG}
    ports:
      - 5858:5858
    group_add:
      - video
    devices:
      - "/dev/video0:/dev/video0"
    restart: always

  frontend:
    image: ${REPOPREFIX}frontend:${TAG}
    ports:
      - 80:80
    restart: always

  rover-api-net:
    image: ${REPOPREFIX}rover-api-net:${TAG}
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/gpiochip0:/dev/gpiochip0"
    volumes:
      - servoblaster:/extdev
    restart: always

  rover-api-http:
    image: ${REPOPREFIX}rover-api-http:${TAG}
    restart: always

volumes:
  servoblaster:

# end