[package]
name = "libapi-http"
version = "0.1.0"
authors = ["Vadym S. Khondar <vadym@khondar.name>"]
edition = "2021"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
strum = "0.26.1"
strum_macros = "0.26.1"