[package]
name = "libdriver"
version = "0.1.0"
authors = ["Vadym S. Khondar <vadym@khondar.name>"]
edition = "2021"

[dependencies]
futures = "0.3.30"
tokio = { version = "1.36.0", features = ["default", "rt"] }
async-trait = "0.1.77"
anyhow = "1.0.80"
thiserror = "1.0.57"