[package]
name = "libdriver"
version = "0.1.0"
authors = ["Vadym S. Khondar <vadym@khondar.name>"]
edition = "2018"

[dependencies]
futures = "0.3.1"
tokio = { version = "0.2.21", features = ["blocking"] }
async-trait = "0.1.33"
anyhow = "1.0.31"
thiserror = "1.0.19"