[package]
name = "api-http"
version = "0.1.0"
authors = ["Vadym S. Khondar <vadym@khondar.name>"]
edition = "2018"

[dependencies]
config = "0.9"
log = "0.4"
actix-web = "0.7"
libutil = { path = "../libutil" }
