[package]
name = "api-http"
version = "0.1.0"
authors = ["Vadym S. Khondar <vadym@khondar.name>"]
edition = "2018"

[dependencies]
config = "0.9"
log = "0.4"
serde = "1.0.114"
actix-web = "2.0"
actix-rt = "1.1.1"
libutil = { path = "../libutil" }
