[workspace]
members = [
    "api-http",
    "api-net",
    "ux-console",
    "libdriver",
    "libdriver-robohat",
    "libapi-net",
    "libux-console",
    "libutil"
]

exclude = [
    "libux-web"
]
